import os

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
CHANNEL_ID = int(os.getenv("CHANNEL_ID"))
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
ARTIST_NAME = os.getenv("ARTIST_NAME")
CHECK_INTERVAL = 5
